version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php-unit-herencia
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - php-unit-herenncia-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db-php-unit-herencia
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - php-unit-herenncia-network

  nginx:
    image: nginx:alpine
    container_name: nginx-php-unit-herencia
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - php-unit-herenncia-network

networks:
  php-unit-herenncia-network:
    driver: bridge
