version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: api-rest-php
    working_dir: /var/www/api-rest-curso-pl
    volumes:
      - ./src:/var/www
    networks:
      - api-rest-php-network

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db-php
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - api-rest-php-network

  nginx:
    image: nginx:alpine
    container_name: nginx-php
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - api-rest-php-network

networks:
  api-rest-php-network:
    driver: bridge
